version: "3.8"
services:
  PRANK:
    image: 
    environment:
      exposed: "21,25,80,3306,3389"
      host_name: toto
      from_email: 
      to_email: 
      smtp_addr: 
      smtp_port: 25
    volumes:
      - /etc/hostname:/opt/PRANK/hostname
    ports:
      - target: 21
        published: 21
        mode: host
      - target: 25
        published: 25
        mode: host
      - target: 80
        published: 80
        mode: host
      - target: 3306
        published: 3306
        mode: host
      - target: 3389
        published: 3389
        mode: host
